# werf/wait-http-200.yaml
#
{{- define "h-init-container-wait-http-200" -}}
  {{- $ := index . 0 }}
  {{- $url := index . 2 }}
  {{- with index . 1 }}


- name: wait-http-200-{{ print $url | sha256sum | trunc 5 }}
  image: {{ .Values.werf.image.h_wait_http_200 }}
  command:
    - "sh"
    - "-c"
    - >
      while [[ "$(curl -s -o /dev/null -w '%{http_code}' {{ print $url }})" != "200" ]];
      do echo waiting for {{ print $url }};
      sleep 2;
      done


{{- end -}} {{- end -}}
