# werf/promo.yaml
#
{{- define "h-promo" }} {{- $ := index . 0 }} {{- with index . 1 }}


{{- include "h-statefulset-header" (list $ .) }}
      containers:
      - name: promo
        image: {{ .Values.werf.image.promo }}
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - "/root/{{ .Chart.Name }}/build/build__post-start-container.bash"
        workingDir: /var/www/{{ .Chart.Name }}
        env:
        - name: SSH_AUTH_SOCK
          value: /ssh-agent
        - name: ENVIRONMENT
          value: {{ .Values.werf.env }}
        - name: HOME_USER_NAME
          value: {{ .Values.HOME_USER_NAME }}
        ports:
        - containerPort: 80
          name: promo
          protocol: TCP
        volumeMounts:
          - name: ssh-agent-sock
            mountPath: /ssh-agent
          - name: data-store
            mountPath: /var/www
            subPath: {{ .Chart.Name }}-www
      initContainers:
{{- $gitlabUrl := "http://gitlab-prod.gitlab-prod/users/sign_in" }}
{{- include "h-init-container-wait-http-200" (list $ . $gitlabUrl) | indent 6 }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Chart.Name }}-config-files
      - name: data-store
        persistentVolumeClaim:
          claimName: nfs-pvc-{{ .Chart.Name }}-{{ .Values.werf.env }}
      - name: ssh-agent-sock
        hostPath:
          path: /ssh-agent
          type: Socket


{{- end }} {{- end }}
